### ISSUE TITLE
README link for GoCD CI info isn't public

### ISSUE THREAD

**Issue by ches** [cloudfoundry-incubator/bookbinder#26]
The link given for info on the CI system, https://sites.google.com/a/pivotal.io/cf-tools/gocd, does not appear to be public—I'm given an insufficient privileges page when trying to access it.

**Comment by ericTsiliacos** [comment]
Hi @ches,

Thanks for bringing that up. We are currently in the processes of cleaning up the README.md. Upon further inspection, it doesn't seem that link would be very helpful so we are going to remove it.
