### ISSUE TITLE
Document what the header should be for generate_pdf

### ISSUE THREAD

**Issue by ches** [cloudfoundry-incubator/bookbinder#27]
`layout_repo` is an optional setting for `config.yml`, so it's not especially intuitive that it is required by `generate_pdf`, as the source directory of the file referenced by the `header` config key. The rather notable example of [cloudfoundry/docs-book-cloudfoundry][1], for one, doesn't use a `layout_repo`.

Further, if I were building my own book, it's not apparent to me what the header should be. Is it going to render on every page of a generated PDF? I can go dig up what the `--header-html` option of `wkhtmltopdf` is for, but I had to spelunk the source to get even that far—it would be nice if the next person to wonder this got a little more help from the README :smile:

[1]: https://github.com/cloudfoundry/docs-book-cloudfoundry

**Comment by ericTsiliacos** [comment]
Hi @ches,

You are correct. The layout_repo is necessary for the generate_pdf command. We will fix that in the README.md and also provide an example.

**Comment by ches** [comment]
Thanks for the quick clarifications!
